name: Build on request
on: [workflow_dispatch]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
        vcpkgTriplet: x86-windows-static
        vcpkgGitCommitId: 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
        vcpkgArguments: >
          boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem
          luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl

    - name: Integrate vcpkg
      run: |
        ${{ runner.workspace }}/vcpkg/vcpkg integrate install
        
    - name: Compile otclient_dx
      timeout-minutes: 20
      run: |
        cd vc16
        MSBuild /property:Configuration=DirectX /p:BUILD_REVISION=${{github.run_number}}
        
    - name: Compile otclient_gl
      timeout-minutes: 20
      run: |
        cd vc16
        MSBuild /property:Configuration=OpenGL /p:BUILD_REVISION=${{github.run_number}}

    #- name: Sign binaries
    #  run: |
    #     .\tools\sign\signtool.exe sign /f .\tools\sign\certificate.pfx /p ${{ secrets.SIGN_PASSWORD }} /fd SHA256 /t http://timestamp.digicert.com /d "OTclientV8" otclient_gl.exe
    #     .\tools\sign\signtool.exe sign /f .\tools\sign\certificate.pfx /p ${{ secrets.SIGN_PASSWORD }} /fd SHA256 /t http://timestamp.digicert.com /d "OTclientV8" otclient_dx.exe

    - name: Upload binaries
      uses: 'actions/upload-artifact@v2'
      with:
        name: Download-binaries
        path: |
          otclient_gl.exe
          otclient_dx.exe
        if-no-files-found: error



