name: Build on request
on: [workflow_dispatch]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v2
      id: setup_msbuild

    - name: Install vcpkg deps
      shell: pwsh
      run: |
        & $env:VCPKG_INSTALLATION_ROOT\vcpkg install `
          boost-iostreams:x86-windows-static `
          boost-asio:x86-windows-static `
          boost-beast:x86-windows-static `
          boost-system:x86-windows-static `
          boost-variant:x86-windows-static `
          boost-lockfree:x86-windows-static `
          boost-process:x86-windows-static `
          boost-program-options:x86-windows-static `
          boost-filesystem:x86-windows-static `
          boost-uuid:x86-windows-static `
          luajit:x86-windows-static `
          glew:x86-windows-static `
          physfs:x86-windows-static `
          openal-soft:x86-windows-static `
          libogg:x86-windows-static `
          libvorbis:x86-windows-static `
          zlib:x86-windows-static `
          libzip:x86-windows-static `
          bzip2:x86-windows-static `
          openssl:x86-windows-static

    - name: Integrate vcpkg
      shell: pwsh
      run: |
        & $env:VCPKG_INSTALLATION_ROOTcpkg integrate install

    - name: Compile otclient_dx
      timeout-minutes: 20
      run: |
        cd vc16
        MSBuild /property:Configuration=DirectX /p:BUILD_REVISION=${{github.run_number}}
        
    - name: Compile otclient_gl
      timeout-minutes: 20
      run: |
        cd vc16
        MSBuild /property:Configuration=OpenGL /p:BUILD_REVISION=${{github.run_number}}

    #- name: Sign binaries
    #  run: |
    #     .\tools\sign\signtool.exe sign /f .\tools\sign\certificate.pfx /p ${{ secrets.SIGN_PASSWORD }} /fd SHA256 /t http://timestamp.digicert.com /d "OTclientV8" otclient_gl.exe
    #     .\tools\sign\signtool.exe sign /f .\tools\sign\certificate.pfx /p ${{ secrets.SIGN_PASSWORD }} /fd SHA256 /t http://timestamp.digicert.com /d "OTclientV8" otclient_dx.exe

    - name: Upload binaries
      uses: 'actions/upload-artifact@v4'
      with:
        name: Download-binaries
        path: |
          otclient_gl.exe
          otclient_dx.exe
        if-no-files-found: error



